server:
  port: 8081
  servlet:
    context-path: /api/v1/profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
logging:
  level:
    org.springframework.data.neo4j: DEBUG
    org.neo4j.ogm.drivers.bolt.request: DEBUG

