server:
  port: 8081
  servlet:
    context-path: /api/v1/profile
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profile_service
    username: admin
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


