server:
  port: 8080
  servlet:
    context-path: /api/v1/identity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: admin
    password: 1
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

jwt:
  signerKey: "bj0hKxleZxWk8mHcrceJBce84L5qniIsLM3UcEw6NZWiyTXXN3zTVFoBRB0BScPz"
  validDuration: 9999
  refreshableDuration: 9999

app:
  service:
    profile: http://localhost:8081/api/v1/profile
